version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"

  loans-service:
    build: ./loans-service
    ports:
      - "8001:8000"

  accounts-service:
    build: ./accounts-service
    ports:
      - "8002:8000"

  payments-service:
    build: ./payments-service
    ports:
      - "8003:8000"

  risk-service:
    build: ./risk-service
    ports:
      - "8004:8000"

  notifier-service:
    build: ./notifier-service
    ports:
      - "8005:8000"
